### ISSUE TITLE
RuntimeError from scan_log4j_versions.py in case of encrypted zip

### ISSUE THREAD

**Issue by yan12125** [jfrog/log4j-tools#7]
```
$ python3.6 scan_log4j_versions.py /
Traceback (most recent call last):
  File "scan_log4j_versions.py", line 227, in <module>
    run_scanner(root_dir, set(exclude_dirs))
  File "scan_log4j_versions.py", line 181, in run_scanner
    test_file(file, rel_path)
  File "scan_log4j_versions.py", line 127, in test_file
    next_file = jarfile.open(file_name, "r")
  File "/usr/lib/python3.6/zipfile.py", line 1429, in open
    "required for extraction" % name)
RuntimeError: File 'boot/classworlds-1.1.jar' is encrypted, password required for extraction
```
The error is from a test file in apache-commons-compress: https://gitbox.apache.org/repos/asf?p=commons-compress.git;a=blob;f=src/test/resources/password-encrypted.zip;h=939029cd68c2969df268bc7eec63900c0f1a7196;hb=HEAD

I think the scanner can report such errors and continue on scanning other files?

**Comment by ilya-k-1** [comment]
Thanks for reporting @yan12125 !
Fixed as you suggested in the latest commit

**Comment by yan12125** [comment]
It works! Thanks for the fast fix!
